name = "my_chess_green_agent"
description = "The assessment hosting agent for chess-bench."
version = "0.1.0"

defaultInputModes = ["text"]
defaultOutputModes = ["text"]
[capabilities]
streaming = false

[[skills]]
id = "host_assess_chess_bench"
name = "Chess benchmark assessment hosting"
description = """
Assess the tool-calling ability of an agent.
"""
tags = ["green agent", "assessment hosting", "chess-bench"]
examples = ["""    
Your task is to instantiate a chess benchmark to test the agent located at:
<white_agent_url>
http://localhost:9002/
</white_agent_url>
You should use the following env configuration:
<env_config>
{
  "env": "retail",
  "user_strategy": "llm",
  "user_model": "openai/gpt-5.1",
  "user_provider": "openai",
  "task_split": "test",
  "task_ids": [
    1
  ]
}
</env_config>
    """]
